### ISSUE TITLE
License

### ISSUE THREAD

**Issue by lijiunderstand** [kate-mcardle/tree-based-parallel-kNN#1]
Hi, I want to use and modify your code in our clustering project , and it will be great if you set a license that let us use it freely (like MIT license) , Thank you!

**Comment by kate-mcardle** [comment]
All set! I haven't touched this code in 8 years so it's probably quite outdated :) Best of luck with your project!

**Comment by lijiunderstand** [comment]
Thank you so much! Really appreciate it!
